name: RebelItems
version: ${project.version}
main: com.mcrebels.rebelitems.rebelitems.RebelItems
api-version: 1.16
authors: [xSolum]
description: Adds Custom items

commands:
  rebelitemgive:
  showgui:
